apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: default
spec:
  selector:
    app: eks-sample-linux-app
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080