apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoapp
spec:
  selector:
    matchLabels:
      app: mongoapp
  template:
    metadata:
      labels:
        app: mongoapp
    spec:
      containers:
      - name: mongoapp
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: user-name
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password

---
## This is for internal service creation

apiVersion: v1
kind: Service
metadata:
  name: mongo-service

spec:
  selector:
    app: mongoapp
  #type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017 
